[package]
name = "semverver"
description = "Automatic verification of SemVer adherence in Rust library crates"
repository = "https://github.com/rust-dev-tools/rust-semverver"
readme = "README.md"
keywords = ["semver", "plugin"]
categories = ["development-tools", "development-tools::cargo-plugins"]
version = "0.1.46"
authors = ["Inokentiy Babushkin <twk@twki.de>"]
license-file = "LICENSE"
edition = "2018"

[dependencies]
cargo = "0.50"
crates-io = "0.31" # Keep in sync with version pulled by Cargo
curl = "0.4.21"
env_logger = "0.8"
anyhow = "1.0.38"
log = "0.4"
semver = "0.10" # Keep in sync with version pulled by Cargo
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0.61"

[dev-dependencies]
quickcheck = "1.0"
